### ISSUE TITLE
No Angular Touch here

### ISSUE THREAD

**Issue by Rajan** [AppGyver/supersonic-kitchensink#8]
Hello,

I was working with AngularTouch or Angular Gestures components.
The combination of cross-view communication and AngularTouch/AngularGestures invariably fails.
It'd be great if we address this issue in this kitchensink app.

Best,
Rajan

**Comment by pre** [comment]
Please a question with details [in the forums](https://forums.appgyver.com). There shouldn't be any reason why these libraries couldn't be used with AppGyver.

As a rule of thumb, any file under `dist/` folder will be served from `http://localhost` in the device. Write the path to `<script src="..">` accordingly. You can [inspect the application](http://docs.appgyver.com/tooling/cli/debugging/debugging-on-ios/) using the Safari Debugger and Chrome DevTools.
